version: "3.8"
services:
  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8000"
    restart: unless-stopped
    command: sh -c "pdm run init & pdm run manage runserver 0.0.0.0:8000"
    volumes:
      - ./docs:/app/docs
volumes:
  pgdata:
