version: "3.8"
services:
  mkdocs-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: mkdocs serve -a 0.0.0.0:8000
    volumes:
      - ./docs:/app/docs
