name: hanazono
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pwd}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-8000}:8000"
    restart: unless-stopped
    command: sh -c "pdm run init & pdm run gunicorn hanazono_conf.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./docs:/app/docs
  redis:
    image: 'redis:7.2.0'
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:
