version: "3.8"
services:
  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  site:
    build:
      context: .
      dockerfile: Dockerfile
    command: pdm run site
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./docs:/app/docs
      - site:/app/src/site
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - site:/app/src/site
    command: pdm run manage runserver 0.0.0.0:8000
volumes:
  site:
  pgdata:
