# Generated by Django 4.2.6 on 2023-10-21 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leitner", "0002_flashcard_html"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcard",
            name="buttons",
        ),
    ]
