name: build & deploy on hosts

on:
  push:
    branches: [ "notes" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4

    - name: Init Submodules
      run: git submodule update --init --recursive

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: Dockerfile.standalone
        push: true
        tags: |
          gamnes/hanazono-server:${{ github.run_number }}
          gamnes/hanazono-server:latest
  render-deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  azure-deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to azure
        run: curl ${{ secrets.AZURE_DEPLOY_HOOK }}