name: build & deploy on hosts

on:
  push:
    branches: [ "notes" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4

    - name: Init Submodules
      run: git submodule update --init --recursive

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: Dockerfile.standalone
        push: true
        tags: |
          gamnes/hanazono-server:${{ github.run_number }}
          gamnes/hanazono-server:latest

  render:
    needs: build
    uses: ./.github/workflows/deploy_template.yml
    with:
      host: https://hanazono.onrender.com
      environment: prod
    secrets:
      deploy_hook: ${{ secrets.RENDER_DEPLOY_HOOK }}

  azure:
    needs: build
    uses: ./.github/workflows/deploy_template.yml
    with:
      host: https://hanazono.azurewebsites.net
      environment: prod
    secrets:
      deploy_hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
