name: tests

on:
  push:
    branches:
    - main
jobs:
  tests:
    runs-on: ubuntu-latest
    environment: tests # Github environment name, to use vars context
    env:
      POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      DJANGO_SETTINGS_MODULE :  ${{ vars.DJANGO_SETTINGS_MODULE }}
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - ${{ vars.POSTGRES_PORT }}:5432

    steps:
      - uses: actions/checkout@v4

      - name: Init Submodules
        run: git submodule update --init --recursive

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install --without aiassistant

      - name: Run init
        env:
          DJANGO_SUPERUSER_USERNAME: ${{ vars.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD:  ${{ vars.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUPERUSER_EMAIL: ${{ vars.DJANGO_SUPERUSER_EMAIL }}
        run: pdm run init

      - name: Run tests
        run: pdm run test
